environment:
  stack_root: 'C:\sr'
  tmp: 'C:\tmp'

cache:
  - '%LocalAppData%\Programs\stack -> stack.yaml'
  - 'C:\sr'

before_build:
  - choco install haskell-stack

build_script:
  - stack --no-terminal --install-ghc test
  - stack --no-terminal --local-bin-path . install

after_build:
  - 7z a dhash-windows.zip dhash.exe README.md

artifacts:
  - path: dhash-windows.zip
    name: Release
