environment:
  tmp: 'C:\tmp'

cache:
  - 'C:\SR'

before_build:
  - choco install -y cabal
  - choco install -y ghc --version 8.8.4
  - refreshenv

build_script:
  - cabal update
  - cabal build
  - cabal install --installdir=.

after_build:
  - 7z a dhash-windows.zip dhash.exe README.md

artifacts:
  - path: dhash-windows.zip
    name: Release

deploy:
  provider: GitHub
  auth_token:
    secure: w+mU/6hVeIA/syTrgCb8ypIFACJUlPAKlg3Cc0JWlbQEiNJUn9PjLcVklvIJuWp+
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: $(APPVEYOR_REPO_COMMIT_MESSAGE)
  draft: true
  artiface: /.*\.zip/
  on:
    APPVEYOR_REPO_TAG: true
