name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/cache@v1
        with:
          path: ~/.stack
          key: ${{ hashFiles('stack.yaml') }}

      - uses: actions/setup-haskell@v1
        with:
          ghc-version: '8.6.5'
          cabal-version: '3.0'

      - name: stack config
        run: |
          mkdir -p ~/.stack/
          echo 'system-ghc: true' > ~/.stack/config.yaml

      - name: build
        run:
          stack build

      - name: lint
        run: |
          curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/run.sh | sh -s src
